### ISSUE TITLE
Issue where you can destroy bedrock and every other block in the game with your bare hand

### ISSUE THREAD

**Issue by Thepigcat76** [huskcasaca/effortless-fabric#12]
when selecting the build single block mode and then left click to destroy you can instant break every block in the game even bedrock!

**Comment by Walteryeet** [comment]
It's a feature

**Comment by Thepigcat76** [comment]
That doesnt make it survival playable is there something like a config to disable some of the more op parts of the mod?

**Comment by huskcasaca** [comment]
Okay try this https://github.com/huskcasaca/effortless-fabric/releases/tag/v1.6.0
