### ISSUE TITLE
after placing something with Effortless Fabric the game freeze

### ISSUE THREAD

**Issue by DARKLOL680** [huskcasaca/effortless-fabric#16]
![2022-12-31_22 35 06](https://user-images.githubusercontent.com/121734819/210156048-2fc8bbac-7cb7-424f-b3a9-3f6682981f25.png)
![2022-12-31_22 35 46](https://user-images.githubusercontent.com/121734819/210156051-f0851c20-feb3-430d-94f7-e902f1eaa1f2.png)

**Comment by huskcasaca** [comment]
Any logs? Maybe you can try the latest release.

**Comment by DARKLOL680** [comment]
> Any logs? Maybe you can try the latest release.

i have the latest release installed
[latest.log](https://github.com/huskcasaca/effortless-fabric/files/10328752/latest.log)

**Comment by huskcasaca** [comment]
Just remove other mods to see if there's any conflicts.
