### ISSUE TITLE
Mirror

### ISSUE THREAD

**Issue by DuckXGG** [huskcasaca/effortless-fabric#19]
Mirror only goes from north to south. I want it sometimes to go from east to west

**Comment by huskcasaca** [comment]
It supports 3 axes.

**Comment by DuckXGG** [comment]
Hmm. I tried 3 axes but I don't understand how I make that work like the other mirror just from east to west

**Comment by huskcasaca** [comment]
There is an axis section in mirror settings. Check axis z for east to west, x for north to south, y for up to down, and you can also combine them together.

**Comment by huskcasaca** [comment]
![Preview](https://user-images.githubusercontent.com/100605532/210701485-17b92542-21aa-49ce-a9f7-942c8c4b7ce7.png)

**Comment by DuckXGG** [comment]
ty that works
