### ISSUE TITLE
Gradlew build failure

### ISSUE THREAD

**Issue by Phen0n** [huskcasaca/effortless-fabric#24]
![image_2023-01-29_220729829](https://user-images.githubusercontent.com/108618959/215353027-13a45bd0-7093-4770-bc3f-08717b5b011f.png)

**Comment by huskcasaca** [comment]
`git clone --recursive`

**Comment by Phen0n** [comment]
![image](https://user-images.githubusercontent.com/108618959/215588784-1be6bc46-3093-48a6-9c8a-559cda33f43a.png)

**Comment by huskcasaca** [comment]
Check your `JAVA_HOME`

**Comment by Phen0n** [comment]
`JAVA_HOME` was set to `C:\Program Files\Java\jdk-18.0.1` and changing it didn't work. I ultimately got it to work by removing the JRE altogether.
