### ISSUE TITLE
my game crashed when I clicked the settings button

### ISSUE THREAD

**Issue by vinnyg0621** [huskcasaca/effortless-fabric#5]
https://hastebin.com/yuvejozufa.yaml

**Comment by vinnyg0621** [comment]
also, the undo button doesn't do anything at all. when I tried to click it, my work was still there! 😠

**Comment by huskcasaca** [comment]
You need [cloth config](https://www.curseforge.com/minecraft/mc-mods/cloth-config) installed. Undo/Redo is still in TODO list.

**Comment by huskcasaca** [comment]
Cloth config is now a build-in lib.
