### ISSUE TITLE
A lot of server error suppression with effortless installed

### ISSUE THREAD

**Issue by netcore10** [huskcasaca/effortless-fabric#7]
https://mclo.gs/HL3oU88

**Comment by netcore10** [comment]
I couldn't replicate it once removing it.

**Comment by huskcasaca** [comment]
Try v1.4.2
https://github.com/huskcasaca/effortless-fabric/releases/tag/v1.4.2

**Comment by netcore10** [comment]
Works as expected, no log spam!
